/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:Food:563157:
  println("Food - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:Food:563157:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  Food = new GDropList(this, 189, 150, 90, 120, 5, 10);
  Food.setItems(loadStrings("list_563157"), 0);
  Food.addEventHandler(this, "dropList1_click1");
}

// Variable declarations 
// autogenerated do not edit
GDropList Food; 
